name: stringcompare

dependencies:
  - python=3.7.9
  - pip
  - ipython
  - jupyter
  - pytest
  - numpy
  - pip:
    - pybind11
    - jellyfish
    - py_stringmatching
    - textdistance
    - myst-parser
    - sphinx
    - sphinx-rtd-theme
    - m2r
